---
title: "plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# plotly

we're making interactive plots 
```{r}
library(tidyverse)
library(plotly)
library(p8105.datasets)

```

```{r}
data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```



let's make a scatterplot~ 

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", stars)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    type = "scatter", mode = "markers", text = ~text_label, alpha = 0.5) 
```

let's make a box plot! 

```{r}
nyc_airbnb %>% 
  mutate(neighborhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

let's make a bar plot!

```{r}

nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```


## ggplotly

ggplot scatterplot -- don't do this

```{r}
ggp_scatter = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) + 
  geom_point(alpha = .5)

ggplotly(ggp_scatter)
```


